name: Pull request to Org Main

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      # 1. 
      - name: 1. Start of build-and-upload workflow
        run: echo "Start of build-and-upload workflow"
      # 2.
      - name: 2. List Files
        run: |
          pwd
          ls -ltrh
      # 3.
      - name: 3. Update and Upgrade Enviornment
        run: |
          sudo apt-get update
          sudo apt-get -qy upgrade
      # 4. 
      - name: 4. Install Java 11
        run: |
          # sudo apt-get install -y openjdk-11-jdk
          # java -version
          # export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          # export PATH=$JAVA_HOME/bin:$PATH
      # 5. 
      - name: 5. Install Maven
        run: |
          # sudo apt install maven -y
      # 6. 
      - name: 6. Install AWS CLI
        run: |
          cd ~
          sudo apt-get install -y python3-pip
          python -m pip install awscliv2
          aws --version
      # 7.
      - name: 7. Generate build
        run: |
          cd /home/runner/work/serverless/serverless/
          # mvn clean install
          zip SendEmail.zip index.js
      # 8.
      - name: 8. Setup AWS profile
        run: |
          aws configure set region ${{ secrets.SERVERLESS_AWS_REGION }} --profile default
          aws configure set aws_access_key_id ${{ secrets.SERVERLESS_AWS_ACCESS_KEY }} --profile default
          aws configure set aws_secret_access_key ${{ secrets.SERVERLESS_AWS_SECRET_ACCESS_KEY }} --profile default
      # 9. 
      - name: 9. Perform deployment
        run: |
          # cp /home/runner/work/serverless/serverless/target/lambda_function-1.0-SNAPSHOT.jar .
          aws lambda update-function-code --function-name send_verification_email --region ${{ secrets.SERVERLESS_AWS_REGION }} --zip-file fileb://SendEmail.zip
      # 10.
      - name: 10. End of build-and-upload workflow
        run: echo "End of build-and-upload workflow.." 